---
- name: Install and start Apache (httpd)
  hosts: localhost
  become: true

  tasks:
    - name: Ensure httpd is installed
      package:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Open firewall for HTTP (if firewalld is running)
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_facts.services["firewalld.service"].state == "running"
      ignore_errors: true